<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'app\\emailservice' => '/EmailService.php',
                'app\\orderservice' => '/OrderService.php',
                'app\\pdoorderservice' => '/PdoOrderService.php',
                'app\\servicefactory' => '/ServiceFactory.php',
                'app\\statusprinter' => '/StatusPrinter.php',
                'app\\stockservice' => '/StockService.php',
                'app\\weborderservice' => '/WebOrderService.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
