<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'app\\checkpointrepository' => '/CheckpointRepository.php',
                'app\\inboxrepository' => '/InboxRepository.php',
                'app\\messagebroker' => '/MessageBroker.php',
                'app\\orderservice' => '/OrderService.php',
                'app\\outboxrepository' => '/OutboxRepository.php',
                'app\\servicefactory' => '/ServiceFactory.php',
                'app\\statusprinter' => '/StatusPrinter.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
